package fr.godox.replikube.scripting

import fr.godox.replikube.core.GridSize
import fr.godox.replikube.dsl.Replikube

/**
 * Turns a player's source into a compilable Kotlin file.
 *
 * The player writes **the body of `block`**, and the game supplies everything around it:
 *
 * ```kotlin
 * package replikube.generated
 *
 * import fr.godox.replikube.dsl.*
 *
 * object Level { const val sizeX = 3; ... }
 *
 * class Solution : Replikube {
 *     override fun block(x: Int, y: Int, z: Int): Int? {
 *         // ---- player code, verbatim ----
 *         return when (y) {
 *             1 -> RED
 *             else -> null
 *         }
 *         // ---- end player code ----
 *     }
 * }
 * ```
 *
 * ### Why splice into a block body rather than an expression body
 *
 * An expression body (`= <player code>`) would be one keystroke shorter, but it would
 * forbid a `val`, a loop, an early `return`, or a local helper — and a puzzle about
 * building a spiral needs all four. A block body costs exactly one `return` per exit path
 * and permits anything a function body can contain. Since the player's code becomes the
 * body, their helper declarations become *local* declarations, which is why a level that
 * used a top-level `fun` now writes the same `fun` inside the body.
 *
 * A block body is also what makes `null` the natural way to leave a voxel empty: every
 * colour expression ends in `null`, and `else -> null` reads as "nothing here" without the
 * player having to know that "no cube" is the number 0.
 *
 * ### Line numbering
 *
 * The player's lines keep their original numbering relative to the wrapper, so
 * [GeneratedSource] records [playerLineOffset] to map a compiler-reported line back to the
 * line the player is actually looking at.
 *
 * @property text the file handed to the compiler.
 * @property playerLineOffset the 1-based line in [text] where the player's code starts.
 * @property playerCode the player's code, as normalised into [text].
 */
data class GeneratedSource(
    val text: String,
    val playerLineOffset: Int,
    val playerCode: String,
) {
    /** The player's own lines, 1-based via `playerLines[n - 1]`. */
    val playerLines: List<String> = playerCode.split("\n")

    /** The player's source line for a 1-based line in [text], or `null` if outside the player region. */
    fun toPlayerLine(line: Int): Int? =
        (line - playerLineOffset + 1).takeIf { it in 1..playerLines.size }
}

/** Fully-qualified name of the class the generated file declares. */
const val SOLUTION_CLASS_NAME: String = "replikube.generated.Solution"

/** Package the generated file is placed in. Deliberately not the game's package. */
const val SOLUTION_PACKAGE: String = "replikube.generated"

/** Builds the wrapper around player code. Pure and synchronous — trivially testable. */
object SolutionCompiler {
    /**
     * Wrap the body of `block` that [playerCode] holds, for a grid of [size].
     *
     * Imports cover the whole player-facing API so solutions never need an import line;
     * `Geometry.kt` is `@file:JvmName`d, so its functions arrive via `import ...Geometry.*`.
     */
    fun generate(playerCode: String, size: GridSize): GeneratedSource {
        val marked = buildString {
            appendLine(header(size))
            appendLine()
            appendLine("class Solution : Replikube {")
            appendLine(SIGNATURE)
            appendLine(PLAYER_MARKER)
            appendLine("    }")
            appendLine("}")
        }
        // The player's region is located with a marker rather than by counting lines in the
        // prefix. `String.lines()` drops or keeps the empty element after a trailing newline
        // depending on the toolchain, and an off-by-one here sends every diagnostic to a
        // line the player cannot see — a failure that still *looks* like it works.
        val playerLineOffset = marked.split("\n").indexOf(PLAYER_MARKER) + 1
        val body = playerCode.trimEnd('\n')
        return GeneratedSource(marked.replace(PLAYER_MARKER, body), playerLineOffset, body)
    }

    /** Stands in for the player's code while the wrapper is assembled. Never survives [generate]. */
    private const val PLAYER_MARKER = "// <<< replikube:player-code >>>"

    /**
     * The declaration the player never has to write.
     *
     * `Int?` so that `null` can mean "no cube" — see [Replikube]. A block body rather
     * than an expression body, so the player may use statements; see the class doc.
     */
    private const val SIGNATURE = "    override fun block(x: Int, y: Int, z: Int): Int? {"

    private fun header(size: GridSize): String = """
        |// Generated by replikube. Do not edit.
        |package $SOLUTION_PACKAGE
        |
        |import fr.godox.replikube.dsl.*
        |import kotlin.math.abs
        |import kotlin.math.max
        |import kotlin.math.min
        |
        |/** Dimensions of the grid being filled. */
        |object Level {
        |    const val sizeX = ${size.x}
        |    const val sizeY = ${size.y}
        |    const val sizeZ = ${size.z}
        |
        |    const val minX = -sizeX / 2
        |    const val maxX = (sizeX - 1) / 2
        |    const val minY = -sizeY / 2
        |    const val maxY = (sizeY - 1) / 2
        |    const val minZ = -sizeZ / 2
        |    const val maxZ = (sizeZ - 1) / 2
        |
        |    /** Whether (x, y, z) is inside this grid. */
        |    fun inBounds(x: Int, y: Int, z: Int): Boolean =
        |        x in minX..maxX && y in minY..maxY && z in minZ..maxZ
        |}
    """.trimMargin().trim('\n')
}

/** The player's contract, and the starter template for a grid of a given [size]. */
object SolutionTemplate {
    /**
     * A minimal, compiling starting point for a grid of [size].
     *
     * Prefilled solutions should compile — a player who presses Run on an untouched
     * editor sees a real (empty) result, not a wall of errors.
     */
    fun starter(size: GridSize): String = """
        |// Return a colour for each voxel. null means leave it empty.
        |//
        |// x, y, z range over the level's grid, centred on the origin:
        |//   x in ${-size.x / 2}..${(size.x - 1) / 2}
        |//   y in ${-size.y / 2}..${(size.y - 1) / 2}   (-${size.y / 2} is the bottom layer)
        |//   z in ${-size.z / 2}..${(size.z - 1) / 2}
        |//
        |// Colours: WHITE=1 RED=6 YELLOW=8 GREEN=10 BLUE=12 ... any of them.
        |// Handy helpers: chebyshev(), manhattan(), dist(), parity(), Level.inBounds()
        |
        |return null
    """.trimMargin()
}